### PR TITLE
Hide table and show message when there are no scan errors

### LINKED ISSUE #38: Reports page - what to show when there are no scan errors
Table of scan errors removed and a message shown instead?

### PR DESCRIPTION
**Pull request by jseppi**
Looks like this:

screen shot 2016-05-03 at 11 15 06 am

Ready for review. Closes #38.

### CODE REVIEW

**Comment by juliasolorzano** [comment]
@jseppi can you add a screen for what it looks like when scans are not passing?

**Comment by jseppi** [comment]
I'm in transit and won't be able to do that for a while, but it looks like
what is currently in master branch (the table of type, risk, and
description).

**Comment by juliasolorzano** [comment]
Ah! No worries and safe travels! 😄

Would it be possible to add a link to that report, rather than list out the errors in the warning? As mentioned in the wireframes, it would state "Scans returned [x] number errors." and then possibly link to the table below.

**Comment by DavidEBest** [comment]
@juliaelman This is for the report page, which does list the individual alerts.

**Comment by juliasolorzano** [comment]
@DavidEBest ah! I see now. I thought this was part of the header alerts. Dis-regard my comment and LGTM! 👍

**Pull request merged**
