### PR TITLE
Report page styling

### LINKED ISSUE #32: Improve styling on the report page
Breaking out from #28 
- [x] Add back arrow to "Project List page" link at the top of the page
- [x] Add spacing (see wireframe) for the top portion of the page (see image below).
- [x] Make "Updated..." italicized
- [x] Add relevant links to each bullet point under "Getting Started"
  - First one: https://pages.18f.gov/before-you-ship/
  - Second one: https://pages.18f.gov/before-you-ship/ato/checklist/
- [x] Add a visual indicator for sortability to the Type & Risk columns

Wireframe
cv-wireframes-v3_page_3

### PR DESCRIPTION
**Pull request by jseppi**
Ready for review.

Closes #32.

### CODE REVIEW

**Comment by DavidEBest** [comment]
Looking good. 

Two things:

Would you mind increasing the spacing between the project name and 'Getting Started'?

screenshot 2016-05-02 14 09 08

and 

Don't know how I missed this before -- the 'All scans passing' line should be dynamic. It should only be 'All scans passing' if there are no alerts. Otherwise, it should be 'Scans returned X errors', where X is the number of errors in the table.

**Comment by jseppi** [comment]
on it

**Comment by jseppi** [comment]
@DavidEBest: Just to be clear, the number of errors to show in the status bar message is `report_data['alerts'].length`, correct?

**Comment by DavidEBest** [comment]
@jseppi Yup. That'll work for the time being.

**Comment by jseppi** [comment]
Ready for review again.

**Comment by DavidEBest** [comment]
Looks very good. One thing - could you make the `Type` column default to wider?

screenshot 2016-05-02 16 31 38

**Pull request merged**
