### PR TITLE
Vendoring the cloudgov_style assets for use in Compliance Viewer.

### PR DESCRIPTION
**Pull request by DavidEBest**
The cloudgov_style gem does not work with the sprockets asset pipeline, as implemented in Sinatra. I vendored the assets for the timebeing.

### CODE REVIEW

**Comment by juliasolorzano** [comment]
Aha! I was wondering if there was an asset pipeline tool for Sinatra and was talking with @afeld about this yesterday.

@DavidEBest we'd probably want to install the `cg-style` package via `npm`, per the README documentation found [here](https://github.com/18F/cg-style#install-and-use). We'll be adding a `package.json` file to the repo, but the win is that we'll be able to update the styles easily as they continue to grow/change.

Doing this will also give us the opportunity to use Sass too! 👍

**Comment by DavidEBest** [comment]
Thanks for the feedback. I'll give it a shot! There is a functional sinatra asset pipeline (https://github.com/kalasjocke/sinatra-asset-pipeline), but the cg_style gem doesn't work with it (or, based on some of the issues, Rails).

**Comment by msecret** [comment]
Yea because we were only using cg-style with jekyll, we didn't put any effort getting it to work with other Ruby frameworks. There was an attempt to get it working for Rails, but that attempt was mainly just taking patterns from the Web Design Standards (WDS) gem and applying it to cg-style (which I think doesn't work anyway).

If you don't want to include nodejs and npm as a dependency on the project, it might be a good idea to look into how to make cg-style work with the sprockets asset pipeline or any ruby framework pipeline. From a front end perspective, it'd be nice if this could be a pattern we could repeat across our other style libraries, such as WDS. 

I would say theres different ways we can do this. One would be to stay in the nodejs/npm land to get Ruby frameworks working: https://github.com/vigetlabs/gulp-rails-pipeline. I like this idea because most front end development at 18F is moving more towards npm, as not every project even includes ruby.

**Comment by DavidEBest** [comment]
@juliaelman @afeld Is this more like what you were thinking?

**Comment by juliasolorzano** [comment]
@DavidEBest almost there! This adds the `cg-style` npm package, but does not give us access to use Sass. We might want to do a few things:

1) Add some sort of pre-processor for compiling Sass to CSS. `gulp` has one that we can use, but would push us away from the `go` script.
2) Import the `cg-style` into a base stylesheet for CV or include it in a base layout `<head>` (along with a CV specific style sheet).

If this does not make sense, happy to help and pair on this with you!

**Comment by DavidEBest** [comment]
@juliaelman Thanks for the feedback. I'll take a look.

**Comment by DavidEBest** [comment]
@juliaelman I've taken a look, and I believe we might need to stick with the css for the MVP. That is the current recommended method. https://18f.slack.com/archives/cloud-gov-frontend/p1461265461000245 . This is definitely something to revisit.

**Comment by juliasolorzano** [comment]
Sounds good - onward!

**Comment by msecret** [comment]
I'd agree this is a great method for MVP.

**Pull request merged**
